# Generated by Django 4.0.5 on 2022-06-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal_app', '0004_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='to_read',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('n', 'News'), ('a', 'Articles')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
